### ISSUE TITLE
sophon-demo/sample/OpenPose/scripts里的下载链接过期了

### ISSUE THREAD

**Issue by FANRONGZENG** [sophgo/sophon-demo#1]
# models
if [ ! -d "../models" ]; 
then
    python3 -m dfn --url http://219.142.246.77:65000/sharing/7vRbmIrTb
    unzip models.zip -d ../
    rm models.zip
    echo "models download!"

你好，提供的下载链接失效了，如果想重新训练相关模型，需要怎么做

**Comment by sophon-chencp** [comment]
该链接测试正常，请提供相应的报错日志。如需重新训练相关模型，请参考官方仓库https://github.com/CMU-Perceptual-Computing-Lab/openpose。
