### ISSUE TITLE
sophon-demo/sample/CenterNet/scripts/download.sh中下载链接失效

### ISSUE THREAD

**Issue by sc-guihub** [sophgo/sophon-demo#12]
python3 -m dfn --url https://219.142.246.77:65000/sharing/WCI0q1dPy下载模型权重失败。
请问能换成dfss下载吗？如果可以dfss的下载链接是什么？
我尝试着使用 python3 -m dfss --url=open@sophgo.com:sophon-demo/CenterNet/models_0918/models.zip，但是找不到。

**Comment by gfwsbsbsb** [comment]
已修复
