### ISSUE TITLE
YOLOv8 在SE5上推理结果异常

### ISSUE THREAD

**Issue by Snowba1l** [sophgo/sophon-demo#16]
问题描述：
 
1. 使用官方的demo提供的BM1684的bmodel推理，yolov8s_int8_4b.bmodel 结果异常
![1702370559793](https://github.com/sophgo/sophon-demo/assets/63241867/ee381b50-f609-4d80-8c53-bea4001c5252)

2. 参考demo转换自己的yolov8s模型推理异常
![image](https://github.com/sophgo/sophon-demo/assets/63241867/0cb1f4b1-dba0-4150-b4b2-909c40645fff)
![image](https://github.com/sophgo/sophon-demo/assets/63241867/5fe0ed2f-6bab-4229-9fb5-dc1478626d6b)

**Comment by gfwsbsbsb** [comment]
无法复现。
yolov8接收的是图片文件夹，是否是因为改动代码导致的？
或者盒子的sdk版本太老，请提供更详细的信息，包括盒子sdk版本（使用bm_version命令查看），mlir版本、docker版本以及是否最新代码等。

**Comment by Snowba1l** [comment]
盒子sdk版本0.4.8
开发SDK版本v23.05.01
sophon-demo 版本sophon-demo_v0.1.6_f4d1abc_20230605
tpu-mlir 版本 tpu-mlir_v1.1.7-g30df2e3c-20230605

目前使用mlir工具链编译官方导出的动态batch，为batch为4的bmodel推理结果异常。
![image](https://github.com/sophgo/sophon-demo/assets/63241867/080a77c6-21aa-456e-804b-c0bb1bad90c4)

bmodel结果:
![3](https://github.com/sophgo/sophon-demo/assets/63241867/7d27581c-f818-4240-8cbb-6bf0ebfaf508)
![000000547383](https://github.com/sophgo/sophon-demo/assets/63241867/63ae4137-adc6-47e1-94cc-0c53d4fa741a)
![dog](https://github.com/sophgo/sophon-demo/assets/63241867/ee2c535d-ddf4-4317-a948-1578ee2ab8ec)
![zidane](https://github.com/sophgo/sophon-demo/assets/63241867/50d3d465-0da9-4336-a0ab-8ce280d1ee7e)


onnx推理结果:
![zidane](https://github.com/sophgo/sophon-demo/assets/63241867/96b279d3-a4c0-4196-8445-780bbb98515c)
![dog](https://github.com/sophgo/sophon-demo/assets/63241867/2098b556-194f-4901-aea7-e1259717698b)
![000000547383](https://github.com/sophgo/sophon-demo/assets/63241867/338c40b9-760b-45da-b6a2-caea19b6d252)
![3](https://github.com/sophgo/sophon-demo/assets/63241867/fd03100c-939a-4518-a915-3a81b2dc554d)

模型转换模型脚本链接：
链接：https://pan.baidu.com/s/1hrGLKVtLUVjoyuLkynZOgg?pwd=8uqf

**Comment by gfwsbsbsb** [comment]
量化效果不好时，首先确认fp32精度是否有问题，如果fp32精度都有问题，那就得看mlir转模型这一步是否有问题，目前yolov8的脚本应该在model_deploy时有加--test_input，比对通过的话精度基本上ok。
如果确认是int8量化带来的精度问题，可以参考sophon-demo/docs/Calibration_Guide.md 设置敏感层。
