### ISSUE TITLE
能不能在之后的版本增加语音合成的例子

### ISSUE THREAD

**Issue by XMUEDUx** [sophgo/sophon-demo#17]
语音合成的应用情景很多，比如把tensorflowtts的h5模型转移过来，给的例子多是torch的。

**Comment by gfwsbsbsb** [comment]
新增一个demo其实还涉及到工具链的适配，目前研发资源较紧张，需要有客户有明确应用需求我们才新增相关demo。

**Comment by szxysdt** [comment]
我做了，基于BERT-VITS2，目前BM1684X跑起来实时率大约为0.3，等优化到0.1之后开源

**Comment by sophon-leevi** [comment]
目前有新增ChatTTS, VITS
