### ISSUE TITLE
SE7盒子 直接使用sophon-demo推理报错

### ISSUE THREAD

**Issue by SweatLin** [sophgo/sophon-demo#18]
linaro@bm1684:~/data/sophon-demo/sample/YOLOv5/python$ python3 yolov5_bmcv.py
[BMRT][bmcpu_setup:406] INFO:cpu_lib 'libcpuop.so' is loaded.
bmcpu init: skip cpu_user_defined
open usercpu.so, init user_cpu_init
[BMRT][load_bmodel:1084] INFO:Loading bmodel from [./yolov5s_231218_1684x_f32.bmodel]. Thanks for your patience...
[BMRT][load_bmodel:1023] INFO:pre net num: 0, load net num: 1
INFO:root:1, img_file: ./input/1.jpg
Open /dev/jpu successfully, device index = 0, jpu fd = 31, vpp fd = 32
[2023-12-20 17:09:23.228] [error] [cvwrapper.cpp:2967] bm_image err = input bm_image must be contiguous!
[2023-12-20 17:09:23.228] [error] [engine.cpp:1093] Input Tensor Error!, Not found device memory in input tensor: images

采用的yolov5_bmcv       

希望大佬给个意见

**Comment by gfwsbsbsb** [comment]
这个模型的输入端出现问题了，如果要跑自己的模型，输入输出shape不一样的话，要改代码，具体可以多了解一下算能官网上面提供的接口文档。
