### ISSUE TITLE
resnet的sample编译时报错

### ISSUE THREAD

**Issue by liumingzhu6060** [sophgo/sophon-demo#2]
resnet的sample在build文件夹下make时，报如下错误：
![image](https://github.com/sophgo/sophon-demo/assets/79501943/60527299-8716-4248-a3e8-03a05c645b02)

**Comment by gfwsbsbsb** [comment]
请确认下交叉编译工具链、soc-sdk的版本。
可以用这个soc-sdk试试：http://disk-sophgo-vip.quickconnect.cn/sharing/M85stwTDN

**Comment by zendfly** [comment]
![image](https://github.com/sophgo/sophon-demo/assets/30382669/5c726f4b-7efa-441b-94dd-31f526f27c8e)
这错误是交叉编译工具链导致的问题么？ sophon-sail是用官方下载的SDK Release_230501-public版
