### ISSUE TITLE
使用samples里提供的chatglm2及llama2刷机包刷镜像后灯没有闪烁，没刷成功；使用官网0.4.6的镜像可以刷机成功

### ISSUE THREAD

**Issue by shanchenjie** [sophgo/sophon-demo#20]
硬件：SE7
软件版本：SDK 0.4.6
1、使用sophon-demo里提供的chatglm2及llama2刷机包刷镜像后灯没有闪烁，风扇也没转，没刷成功，可能是什么原因呢？刷回官网的两个镜像可以刷机成功。
2、盒子类可以不刷镜像直接升级sdk吗？

**Comment by gfwsbsbsb** [comment]
参考该文档检查一下mcu版本
[SE7刷机文档.pdf](https://github.com/sophgo/sophon-demo/files/13971173/SE7.pdf)

**Comment by gfwsbsbsb** [comment]
[mcudebs.zip](https://github.com/sophgo/sophon-demo/files/13971192/mcudebs.zip)

**Comment by shanchenjie** [comment]
非常感谢，已经升级完2307的mcu版本并使用llama2刷机包进行了刷机，当前已经可以正常使用，后续如果官网有新版本后可以直接升级SDK吗？还是必须刷镜像？

**Comment by gfwsbsbsb** [comment]
最好是刷机。具体可以看bsp开发手册，还有tftp等升级方式。

**Comment by shanchenjie** [comment]
好的，谢谢~
