### ISSUE TITLE
使用代理无法通过dfss下载文件

### ISSUE THREAD

**Issue by CHNtentes** [sophgo/sophon-demo#21]
所有下载脚本中的python -m dfss都会报错，如下所示：

dfss tool v1.5.3 by Sophgo
download from open@sophgo.com:/sophon-demo/Stable_diffusion_v1_5/singlize_bmodels.zip
No available servers found.
download num 0
No available servers found.
download num 1
No available servers found.
download num 2

公司网络是用代理服务器的，请问有没有可以使用代理下载文件的方法？

**Comment by gfwsbsbsb** [comment]
我用手机流量开热点都可以下载呀。

**Comment by sophon-leevi** [comment]
你们公司有防火墙吧，这个我们没法处理。
