### ISSUE TITLE
 如何利用代码达到，让一个模型支持多个视频流？

### ISSUE THREAD

**Issue by ijiami-01** [sophgo/sophon-demo#24]
![image](https://github.com/sophgo/sophon-demo/assets/129148313/c7146513-1438-4971-a1c1-bc3809471e53)

你好，以上是我的思维图，目前我的代码是参考了sophon-demo中的yolov5例程，但是有个问题，就是每次新增一个任务（视频流），就需要新建一个yoloV5实例，这样对我的性能有影响，我希望看到的是，如果新增的任务用的是已经在使用的模型，那么就不要再实例化一个新的yolov5，而是继续利用之前已存在的yolov5实例去做检测，要达到这样的效果，我该注意些什么？

PS: 我注意到YoloV5实例实际上是在基于一个BMNNContext m_bmContext的基础上做文章，那么是不是理论上 BMNNContext 的实例越少？对性能提升越大？

**Comment by gfwsbsbsb** [comment]
sophon-demo新增了application模块，可以看看
