### ISSUE TITLE
这个文生图的性能测试的单位是秒吗？

### ISSUE THREAD

**Issue by yuyun2000** [sophgo/sophon-demo#29]
<html>
<body>

测试平台 | 测试模式 | 模型格式 | text_encoder_time | inference_time | vae_decoder time
-- | -- | -- | -- | -- | --
BM1684X SoC | text2img | text_encoder fp32 + singlize unet/vae_decoder fp16 | 51.81 | 5808.30 | 473.05

</body>
</html>

生成一张图要将近两个小时？我觉得很不可思议

**Comment by WaitDumplings** [comment]
这里的单位是ms
