### ISSUE TITLE
yolov8n单通道图，batch>1执行in8,f16,f32demo推理均存在问题

### ISSUE THREAD

**Issue by jiwenfei** [sophgo/sophon-demo#30]
batch>1，单通道输入图像的场景，修改demo中的ff_decode.cpp的jpgDec后
         bm_image_create(handle, height, width, FORMAT_GRAY, DATA_TYPE_EXT_1N_BYTE, &img);
，f32可以正常预测，但f16仍然不行

**Comment by sophon-leevi** [comment]
请描述清楚问题，你的描述里面说f32可以正常预测，但是f16不行。但是题目上说都存在问题。
还有，这种一般和推理没关系，可能是数据没有正常送给模型，你是如何修改jpgDec，需要发出来。
或者你也可以使用sophon-opencv读图，不一定要用ff_decode，通过cv::bmcv::toBMI这个接口把cv::Mat转换成bm_image.

**Comment by jiwenfei** [comment]
目前修改的地方有：
![把图像转为灰度图](https://github.com/sophgo/sophon-demo/assets/14801991/92a12de1-fbe8-4466-8643-74810aad172a)
![预处理修改gpu图片格式](https://github.com/sophgo/sophon-demo/assets/14801991/082f4030-ed00-4c88-82fa-1ce9a7f500ec)
经过上面修改后，
输入图像是灰度图，fp32 batch=4执行能够检出，fp16 batch=4每次推理只有一张图有结果
===============
测试输入图像是rgb图，
fp32 batch4和1 使用官网demo未作修改均可执行。
===============

**Comment by sophon-leevi** [comment]
理论上fp16和fp32的输入输出应该是一样的，请检查一下你的fp16模型，在运行环境上使用tpu_model --info xxx.bmodel，检查一下fp32和fp16的bmodel输入输出是否有不同。

**Comment by hychychyc2** [comment]
fp16加精度比对了吗

**Comment by jiwenfei** [comment]
@hychychyc2 没有加

**Comment by jiwenfei** [comment]
> 有
![](https://github.com/sophgo/sophon-demo/assets/14801991/5ff84f05-d67f-47f7-83d7-b9c35b9b9ae4)
![](https://github.com/sophgo/sophon-demo/assets/14801991/e3bd2fa4-4bf2-4f1e-b3b6-aac6efa58658)

@sophon-leevi

**Comment by jiwenfei** [comment]
> 理论上fp16和fp32的输入输出应该是一样的，请检查一下你的fp16模型，在运行环境上使用tpu_model --info xxx.bmodel，检查一下fp32和fp16的bmodel输入输出是否有不同。

输入输出通道数据和尺寸是一致的
`bmodel version: B.2.2
chip: BM1684X
create time: Mon Mar 25 19:36:45 2024

kernel_module name: libbm1684x_kernel_module.so
kernel_module size: 2051624
kernel_module md5: c8f0d89db45a8374e162fbadacb4b518
==========================================
net 0: [x_defect_f32_b4]  static
------------
stage 0:
input: images, [4, 1, 416, 416], float32, scale: 1, zero point: 0
output: output0_Concat, [4, 6, 3549], float32, scale: 1, zero point: 0

device mem size: 43458560 (coeff: 12361728, instruct: 0, runtime: 31096832)
host mem size: 0 (coeff: 0, runtime: 0)`
@sophon-leevi

**Comment by hychychyc2** [comment]
请问mlir版本是什么版本的，可以先加一个精度比对看一下能否通过

**Comment by jiwenfei** [comment]
> 请问mlir版本是什么版本的，可以先加一个精度比对看一下能否通过

tpu-mlir_v1.2.8

**Comment by hychychyc2** [comment]
请使用最新版本得mlir试一下呢

**Comment by sophon-leevi** [comment]
在model_transform的时候加一下--test_input，参考https://github.com/sophgo/sophon-demo/blob/release/sample/YOLOv5/scripts/gen_int8bmodel_mlir.sh
