### ISSUE TITLE
运行Bmodel失败

### ISSUE THREAD

**Issue by SongIdea** [sophgo/sophon-demo#41]
按照YOLOv5_opt样例下载的bmodel模型与测试用例在执行python3 python/yolov5_opencv.py --input datasets/test --bmodel models/BM1684X/yolov5s_tpukernel_fp32_1b.bmodel --dev_id 0 --conf_thresh 0.5 --nms_thresh 0.5 --tpu_kernel_module_path tpu_kernel_module/libbm1684x_kernel_module.so 
命令时报错是什么原因 谢谢
[BMRT][bmcpu_setup:349] INFO:cpu_lib 'libcpuop.so' is loaded.
bmcpu init: skip cpu_user_defined
open usercpu.so, init user_cpu_init 
[BMRT][load_bmodel:1079] INFO:Loading bmodel from [models/BM1684X/yolov5s_tpukernel_fp32_1b.bmodel]. Thanks for your patience...
[BMRT][load_bmodel:1019] WRONG:Error: runtime arch[BM1684] is not the same with bmodel arch[BM1684X]
[2024-06-26 20:17:57.059] [error] Load models/BM1684X/yolov5s_tpukernel_fp32_1b.bmodel failed

**Comment by sophon-leevi** [comment]
你的设备是1684，这个例程不支持1684
