### ISSUE TITLE
qwen2推理异常

### ISSUE THREAD

**Issue by storyxlx** [sophgo/sophon-demo#42]
安装pip install ./dist/sophon-3.7.0-py3-none-any.whl --force-reinstall

然后运行python python/qwen1_5.py --bmodel models/BM1684X/qwen1.5-1.8b_int4_1dev.bmodel --token python/token_config --dev_id 0 ，发生错误：
Traceback (most recent call last):
  File "/root/sophon/python/qwen1_5.py", line 328, in <module>
    main(args)
  File "/root/sophon/python/qwen1_5.py", line 314, in main
    engine = sail.EngineLLM(args.bmodel, [args.dev_id])

很奇怪为什么EngineLLM没有导入，去安装文件去看也没找到什么异常，修改代码：
engine =  sail.Engine(args.bmodel, args.dev_id, sail.IOMode.SYSIO )

再次运行：
[BMRT][bmcpu_setup:406] INFO:cpu_lib 'libcpuop.so' is loaded.
open usercpu.so, init user_cpu_init 
[BMRT][load_bmodel:1084] INFO:Loading bmodel from [models/BM1684X/qwen1.5-1.8b_int4_1dev.bmodel]. Thanks for your patience...
[BMRT][load_bmodel:1023] INFO:pre net num: 0, load net num: 53
[BMRT][fix_gdma_addr:459] FATAL:gdma dst shouldn't be coeff, origin[0x101ead000], ctx[0x101eb0000]
[2024-06-28 18:25:54.763] [error] Load models/BM1684X/qwen1.5-1.8b_int4_1dev.bmodel failed
还是出错了。

**Comment by sophon-leevi** [comment]
![image](https://github.com/sophgo/sophon-demo/assets/165116912/324c3503-0124-45d5-a84c-cac99a8d54c6)
