### ISSUE TITLE
跑python yolov5例程的问题 

### ISSUE THREAD

**Issue by Onlydrink** [sophgo/sophon-demo#44]
![image](https://github.com/sophgo/sophon-demo/assets/55441895/f7570d76-021c-4ee1-ae3b-d3ac36f5b90a)
BMRuntime internal error.

**Comment by sophon-leevi** [comment]
请提供完整的复现流程，包括不限于以下要素：
1.测试平台
2.测试的SDK版本，包括libsophon sophon-ffmpeg sophon-opencv sophon-sail的版本。
libsophon版本可以通过bm-smi、bm_version命令查看，bm_version命令仅限soc模式下使用。
sophon-ffmpeg sophon-opencv版本可以通过bm_version命令查看，或者查看/opt/sophon下对应文件夹名字的版本号。
sophon-sail版本可以通过pip3 list |grep sophon查看，也可以直接提供源码版本，毕竟sophon-sail是后期安装的。
3.测试输入
4.测试模型
5.测试命令
6.是否有修改代码
