### ISSUE TITLE
TPU_MLIR可以安装在aarch64架构的系统上吗

### ISSUE THREAD

**Issue by xc597** [sophgo/sophon-demo#45]
目前将镜像拉取下来，发现是 amd 架构，无法将镜像文件安装在 aaech64 架构的系统上

**Comment by sophon-leevi** [comment]
暂不支持，TPU-MLIR只支持在x86上做模型转换，并且对CPU 和 内存要求都比较高。

**Comment by xc597** [comment]
我在resnet/download.sh下载以后，没有发现CV186的模型，只有BM的模型文件

**Comment by xc597** [comment]
已解决
