### ISSUE TITLE
运行yolov5-fuse的问题

### ISSUE THREAD

**Issue by Onlydrink** [sophgo/sophon-demo#46]
在bm1688平台上 检测示例里面视频 模型使用的是  yolov5s_v6.1_3output_fp32_1b.bmodel出现问题
![image](https://github.com/sophgo/sophon-demo/assets/55441895/77fa6560-d905-478f-ac8f-0514f8b6168c)

**Comment by sophon-leevi** [comment]
命令参数是怎么设置的？我本地无法复现，YOLOv5_fuse用的是最新版本吗？这个例子6月份才release，为啥你这里的sophon-demo是5月11号的版本？

**Comment by Onlydrink** [comment]
> 命令参数是怎么设置的？我本地无法复现，YOLOv5_fuse用的是最新版本吗？这个例子6月份才release，为啥你这里的sophon-demo是5月11号的版本？

命令参数为  python3 yolov5_opencv.py --input /data/datasets/test_car_person_1080P.mp4   --bmodel "/data/BM1688/yolov5s_v6.1_3output_fp32_1b.bmodel"  --dev_id 0 yolov5_fuse 直接用的是git开源的这个代码 这个sophon-demo 是按照公司给的SDK包下载的  sophonsdk_edge_v1.6_offical_release.zip这个就是下载的SDK包   运行代码时依次出现这三个问题刚开始出现了
![image](https://github.com/sophgo/sophon-demo/assets/55441895/649525cc-7eb6-487e-aaae-b44346705621)
解决之后又出现了
![image](https://github.com/sophgo/sophon-demo/assets/55441895/5bb10e60-107e-4286-b0d7-e4c13302de11)
这个问题 解决之后  又出现了
![image](https://github.com/sophgo/sophon-demo/assets/55441895/20a5537a-ebcf-418d-aff4-3072a6018bc2)

**Comment by sophon-leevi** [comment]
我本地完全无法复现，请确认下你用的模型是不是YOLOv5_fuse提供的模型，自己先定位到更细致的问题。
