### ISSUE TITLE
转换模型中出现Cannot open libusercpu.so, disable user cpu layer.

### ISSUE THREAD

**Issue by xc597** [sophgo/sophon-demo#47]
请问转换模型过程中出现bmcpu init: skip cpu_user_defined
Cannot open libusercpu.so, disable user cpu layer.最后虽然生成了bmodel模型。但是好像relu和backword跳过了
<img width="670" alt="image" src="https://github.com/sophgo/sophon-demo/assets/76147079/9adf63ec-b2bd-4fd2-8c79-1ee30ffcda35">

**Comment by sophon-leevi** [comment]
这个log不影响结果，后续mlir版本会去掉这些log
