### ISSUE TITLE
可以支持多模态模型么，比如InternVL 等

### ISSUE THREAD

**Issue by booty-chw** [sophgo/sophon-demo#49]
如题

**Comment by sophon-leevi** [comment]
Qwen-VL 即将加入，请耐心等候

**Comment by sophon-leevi** [comment]
InternVL也即将加入，预计国庆节后release

**Comment by Dylanooo** [comment]
> InternVL也即将加入，预计国庆节后release

会支持InternVL2-8B吗

**Comment by gfwsbsbsb** [comment]
目前测试过2b和4b，8B理论上也可以支持，可以自己试试。

**Comment by gfwsbsbsb** [comment]
https://github.com/sophgo/sophon-demo/tree/release/sample/InternVL2
