### ISSUE TITLE
DeepSort中FeatureExtractor中的转换系数与模型转换脚本不一致?

### ISSUE THREAD

**Issue by crouchggj** [sophgo/sophon-demo#51]
根据sample/DeepSORT/cpp/deepsort_bmcv/FeatureExtractor.cpp中
```
    // 5.converto, RGB mean std.
    float input_scale = tensor->get_scale();
    input_scale = input_scale * 1.0 / 255.f;
    converto_attr.alpha_0 = input_scale / 0.229;
    converto_attr.beta_0 = -0.485 / 0.229;
    converto_attr.alpha_1 = input_scale / 0.224;
    converto_attr.beta_1 = -0.456 / 0.224;
    converto_attr.alpha_2 = input_scale / 0.225;
    converto_attr.beta_2 = -0.406 / 0.225;

```
其中beta_0、beta_1、beta_2的值为-2.1179、-2.0357、-1.80444

但模型转换脚本sample/DeepSORT/scripts/gen_int8bmodel_mlir.sh中
```
function gen_mlir()
{
    model_transform.py \
        --model_name extractor \
        --model_def ../models/onnx/extractor.onnx \
        --input_shapes [[$1,3,128,64]] \
        --mean 2.1179039,1.9912664,1.772926 \
        --scale 0.0171248,0.017507,0.0174292 \
        --pixel_format rgb  \
        --mlir extractor_$1b.mlir
}

```
根据手上的文档 （x - mean）* scale, 那么beta = - mean * scale，但现在示例中的数据无法对应，这是有什么原因吗？

**Comment by sophon-leevi** [comment]
感谢反馈，确实是写错了，model_transform中的mean应该改成123.7，116.3，103.5

**Comment by crouchggj** [comment]
@sophon-leevi  感谢回复，还有2个问题🙋，麻烦对应下：
1. converto_attr.beta_[0,1,2] 是否还需要乘input_scale?
2. mean和scale操作是基于--pixel_format的色彩空间吗？即先进行BGR到RGB的转换，再进行mean，scale操作吗？

**Comment by sophon-leevi** [comment]
1.不需要，可以查看[bmcv开发指南](https://doc.sophgo.com/sdk-docs/v23.10.01/docs_latest_release/docs/bmcv/reference/html/api/convert_to.html)
2.是的，处理代码可以见tpu-mlir_v1.9.beta.0-94-gf02f98421-20240716/python/utils/preprocess.py

**Comment by crouchggj** [comment]
@sophon-leevi  感谢回复，针对第一个问题

>  1.不需要，可以查看[bmcv开发指南](https://doc.sophgo.com/sdk-docs/v23.10.01/docs_latest_release/docs/bmcv/reference/html/api/convert_to.html)

为什么在：https://github.com/sophgo/sophon-demo/blob/release/sample/CenterNet/cpp/centernet_bmcv/centernet.cpp 会乘上input_scale呢？感觉几个sample中的操作有些矛盾

```
    float input_scale = tensor->get_scale();
    const std::vector<float> mean = {0.40789655, 0.44719303, 0.47026116};
    const std::vector<float> std = {0.2886383, 0.27408165, 0.27809834};

    converto_attr.alpha_0 = input_scale / (std[0] * 255);
    converto_attr.beta_0 = -mean[0] * input_scale / std[0];
    converto_attr.alpha_1 = input_scale / (std[1] * 255);
    converto_attr.beta_1 = -mean[1] * input_scale / std[1];
    converto_attr.alpha_2 = input_scale / (std[2] * 255);
    converto_attr.beta_2 = -mean[2] * input_scale / std[2];
```

**Comment by sophon-leevi** [comment]
这几个sample是不同的人写的，可能习惯不一样，如果是fp32的bmodel，input_scale默认是1，如果是int8的bmodel，会有一个input_scale用来校准输入的数据。

**Comment by crouchggj** [comment]
@sophon-leevi 所以在使用int8的bmodel的时候，input_scale不需要乘以converto_attr.beta_[0,1,2]，是吧？input_scale 只需要作用在alpha参数就行了？

**Comment by sophon-leevi** [comment]
需要乘以beta，converto的公式是kx+b，input_scale是int8模型的输入校准参数，要应用到所有的像素值，也就是input_scale*(kx+b)

**Comment by crouchggj** [comment]
> 需要乘以beta，converto的公式是kx+b，input_scale是int8模型的输入校准参数，要应用到所有的像素值，也就是input_scale*(kx+b)

好的，已经理解了
