### ISSUE TITLE
wenetspeech decoder模型转换报错

### ISSUE THREAD

**Issue by l99500** [sophgo/sophon-demo#54]
项目中有提供wenetspeech encoder模型的转换教程，但是没有提供decoder模型的转换教程。

我使用aishell脚本中的转换方式，指令和报错如下：
```
model_transform.py \
        --model_name wenet_decoder \
        --model_def /workspace/wenet/onnx_streaming_wenetspeech/decoder.onnx \
        --input_shapes [[1,350,256],[1],[1,10,350],[1,10],[1,10,350],[1,10]] \
        --mlir wenet_decoder.mlir
```

```
#24 0x00005598f76cbdd5 (/usr/local/lib/python3.10/dist-packages/tpu_mlir/bin/tpuc-opt+0x7cadd5)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tpu_mlir/python/tools/model_transform.py", line 345, in <module>
    tool.model_transform(args.mlir, args.add_postprocess, args.patterns_count)
  File "/usr/local/lib/python3.10/dist-packages/tpu_mlir/python/tools/model_transform.py", line 60, in model_transform
    patterns = mlir_opt_for_top(mlir_origin, self.mlir_file, add_postprocess, True if patterns_count else False)
  File "/usr/local/lib/python3.10/dist-packages/tpu_mlir/python/utils/mlir_shell.py", line 81, in mlir_opt_for_top
    _os_system(cmd)
  File "/usr/local/lib/python3.10/dist-packages/tpu_mlir/python/utils/mlir_shell.py", line 56, in _os_system
    raise RuntimeError("[!Error]: {}".format(cmd_str))
RuntimeError: [!Error]: tpuc-opt wenet_decoder_origin.mlir --shape-infer --canonicalize --extra-optimize -o wenet_decoder.mlir
```
请问以上报错如何解决，或者能否提供encoder对应的转换教程。

**Comment by ruoningYu** [comment]
您好，请问您使用的onnx模型文件是我们demo中提供的吗？我用您提供的指令是可以正常转换的
`root@19f1a62dc98f:/workspace/wenet# model_transform --model_name wenet_decoder --model_def ../wenet_decoder.onnx --input_shapes [[1,350,25
6],[1],[1,10,350],[1,10],[1,10,350],[1,10]] --mlir wenet_decoder.mlir
2024/08/30 15:20:48 - INFO : TPU-MLIR v1.9-20240715
2024/08/30 15:20:48 - INFO : 
         _____________________________________________________ 
        | preprocess:                                           |
        |   (x - mean) * scale                                  |
        '-------------------------------------------------------'
  config Preprocess args : 
        resize_dims           : same to net input dims
        keep_aspect_ratio     : False
        keep_ratio_mode       : letterbox
        pad_value             : 0
        pad_type              : center
        --------------------------
        mean                  : [0.0, 0.0, 0.0]
        scale                 : [1.0, 1.0, 1.0]
        --------------------------
        pixel_format          : bgr
        channel_format        : nchw

2024/08/30 15:20:48 - INFO : Input_shape assigned
2024/08/30 15:20:50 - INFO : ConstantFolding finished
2024/08/30 15:20:50 - INFO : skip_fuse_bn:False
2024/08/30 15:20:51 - INFO : Onnxsim opt finished
2024/08/30 15:20:51 - INFO : ConstantFolding finished
2024/08/30 15:20:52 - INFO : Save mlir file: wenet_decoder_origin.mlir
[Running]: tpuc-opt wenet_decoder_origin.mlir --shape-infer --canonicalize --extra-optimize -o wenet_decoder.mlir
[Success]: tpuc-opt wenet_decoder_origin.mlir --shape-infer --canonicalize --extra-optimize -o wenet_decoder.mlir
2024/08/30 15:20:52 - INFO : Mlir file generated:wenet_decoder.mlir
root@19f1a62dc98f:/workspace/wenet# `

**Comment by ruoningYu** [comment]
root@19f1a62dc98f:/workspace/wenet# model_transform --model_name wenet_decoder --model_def ../wenet_decoder.onnx --input_shapes [[1,350,256],[1],[1,10,350],[1,10],[1,10,350],[1,10]] --mlir wenet_decoder.mlir

**Comment by l99500** [comment]
我是按照sample/WeNet/docs/WeNetSpeech_Guide.md里面的教程自己导出的模型，按照教程的步骤走，encoder的导出和编译是正常的。但是decoder模型的导出有问题。您这边的decoder模型是基于Aishell的源模型还是基于WeNetSpeech的源模型。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sophgo/sophon-demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月30日(星期五) 下午3:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sophgo/sophon-demo] wenetspeech decoder模型转换报错 (Issue #54)





 
您好，请问您使用的onnx模型文件是我们demo中提供的吗？我用您提供的指令是可以正常转换的
 `
 ***@***.***:/workspace/wenet# model_transform --model_name wenet_decoder --model_def ../wenet_decoder.onnx --input_shapes [[1,350,25
 6],[1],[1,10,350],[1,10],[1,10,350],[1,10]] --mlir wenet_decoder.mlir
 2024/08/30 15:20:48 - INFO : TPU-MLIR v1.9-20240715
 2024/08/30 15:20:48 - INFO :
 _____________________________________________________
 | preprocess:                                           |
 |   (x - mean) * scale                                  |
 '-------------------------------------------------------'
 config Preprocess args :
 resize_dims           : same to net input dims
 keep_aspect_ratio     : False
 keep_ratio_mode       : letterbox
 pad_value             : 0
 pad_type              : center
 --------------------------
 mean                  : [0.0, 0.0, 0.0]
 scale                 : [1.0, 1.0, 1.0]
 --------------------------
 pixel_format          : bgr
 channel_format        : nchw
 
2024/08/30 15:20:48 - INFO : Input_shape assigned
 2024/08/30 15:20:50 - INFO : ConstantFolding finished
 2024/08/30 15:20:50 - INFO : skip_fuse_bn:False
 2024/08/30 15:20:51 - INFO : Onnxsim opt finished
 2024/08/30 15:20:51 - INFO : ConstantFolding finished
 2024/08/30 15:20:52 - INFO : Save mlir file: wenet_decoder_origin.mlir
 [Running]: tpuc-opt wenet_decoder_origin.mlir --shape-infer --canonicalize --extra-optimize -o wenet_decoder.mlir
 [Success]: tpuc-opt wenet_decoder_origin.mlir --shape-infer --canonicalize --extra-optimize -o wenet_decoder.mlir
 2024/08/30 15:20:52 - INFO : Mlir file generated:wenet_decoder.mlir
 ***@***.***:/workspace/wenet#
 `

**Comment by sophon-leevi** [comment]
@l99500 你的input_shapes要调整一下，wenet_speech的流式decoder的input_shapes，应该是：
[[1,350,512],[1],[1,10,350],[1,10],[1,10,350],[1,10]]

**Comment by sophon-leevi** [comment]
model_transform.py  --model_name wenet_decoder --model_def ../decoder.onnx --input_shapes [[1,350,512],[1],[1,10,350],[1,10],[1,10,350],[1,10]] --mlir wenet_decoder.mlir
model_deploy.py --mlir wenet_decoder.mlir --quantize F32 --chip bm1684x --model wenet_decoder_fp32.bmodel

这是我的转换命令，你可以参考一下。
