### ISSUE TITLE
IMPORTANT: LICENSE file required

### ISSUE THREAD

**Issue by lazyparser** [sophgo/sophon-demo#60]
IMPORTANT: LICENSE file required

Hi all,

Thank you for sharing these amazing codes!

I've noticed that the LICENSE file is missing, and we may need it ASAP as the further collaborations will be based on it.

If you need any suggestions or helps on this topic, feel free to contact me.

**Comment by sophon-leevi** [comment]
We already have a BSD LICENSE, at sophon-demo/LICENSE.

**Comment by lazyparser** [comment]
Oops I missed that. Thanks for the clarification.
