### ISSUE TITLE
yolov8_seg推理出错

### ISSUE THREAD

**Issue by lrjj** [sophgo/sophon-demo#67]
使用例程sophon-demo-0.2.5，yolov8_seg,我使用ubuntu编译，然后在bm1684x上面运行，可以成功运行，但是我在bm1684x上面编译，可以编译，但是，不能运行，下面是报错信息：

Open /dev/jpu successfully, device index = 0, jpu fd = 5, vpp fd = 6
vpp pcie run failed
[BMCV VPP DUMP][error]  vpp_dump: 794
[BMCV VPP DUMP][error]  idx 0, batch->num  1
[BMCV VPP DUMP][error]  des_head.crop_id  0, crop_flag 1
[BMCV VPP DUMP][error]  input_format 0x1
[BMCV VPP DUMP][error]  post_padding_enable 0x0
[BMCV VPP DUMP][error]  padding_enable 0x0
[BMCV VPP DUMP][error]  rect_border_enable 0x0
[BMCV VPP DUMP][error]  font_enable 0x0
[BMCV VPP DUMP][error]  con_bri_enable 0x0
[BMCV VPP DUMP][error]  csc_scale_order 0x0
[BMCV VPP DUMP][error]  wdma_form 0x1
[BMCV VPP DUMP][error]  fbc_multi_map 0x0
[BMCV VPP DUMP][error]  src_crop_height 0x2d0
[BMCV VPP DUMP][error]  src_crop_width 0x240
[BMCV VPP DUMP][error]  src_crop_st_x 0x0
[BMCV VPP DUMP][error]  src_crop_st_y 0x0
[BMCV VPP DUMP][error]  src_base_ext_ch0 0x4
[BMCV VPP DUMP][error]  src_base_ext_ch1 0x4
[BMCV VPP DUMP][error]  src_base_ext_ch2 0x4
[BMCV VPP DUMP][error]  src_base_ch0 0x40010000
[BMCV VPP DUMP][error]  src_base_ch1 0x40075400
[BMCV VPP DUMP][error]  src_base_ch2 0x4008e900
[BMCV VPP DUMP][error]  src_stride_ch0 0x240
[BMCV VPP DUMP][error]  src_stride_ch1 0x120
[BMCV VPP DUMP][error]  src_stride_ch2 0x120
[BMCV VPP DUMP][error]  padding_value_ch0 0x0
[BMCV VPP DUMP][error]  padding_value_ch1 0x0
[BMCV VPP DUMP][error]  padding_value_ch2 0x0
[BMCV VPP DUMP][error]  padding_ext_up 0x0
[BMCV VPP DUMP][error]  padding_ext_bot 0x0
[BMCV VPP DUMP][error]  padding_ext_left 0x0
[BMCV VPP DUMP][error]  padding_ext_right 0x0
[BMCV VPP DUMP][error]  src_border_value_r 0x0
[BMCV VPP DUMP][error]  src_border_value_g 0x0
[BMCV VPP DUMP][error]  src_border_value_b 0x0
[BMCV VPP DUMP][error]  src_border_thickness 0x0
[BMCV VPP DUMP][error]  src_border_height 0x0
[BMCV VPP DUMP][error]  src_border_width 0x0
[BMCV VPP DUMP][error]  src_border_st_y 0x0
[BMCV VPP DUMP][error]  src_border_st_x 0x0
[BMCV VPP DUMP][error]  src_font_pitch 0x0
[BMCV VPP DUMP][error]  src_font_type 0x0
[BMCV VPP DUMP][error]  src_font_nf_range 0x0
[BMCV VPP DUMP][error]  src_font_dot_en 0x0
[BMCV VPP DUMP][error]  src_font_value_r 0x0
[BMCV VPP DUMP][error]  src_font_value_g 0x0
[BMCV VPP DUMP][error]  src_font_value_b 0x0
[BMCV VPP DUMP][error]  src_font_ext 0x0
[BMCV VPP DUMP][error]  src_font_height 0x0
[BMCV VPP DUMP][error]  src_font_width 0x0
[BMCV VPP DUMP][error]  src_font_st_x 0x0
[BMCV VPP DUMP][error]  src_font_st_y 0x0
[BMCV VPP DUMP][error]  src_font_addr 0x0
[BMCV VPP DUMP][error]  output_format 0x13
[BMCV VPP DUMP][error]  cb_coeff_sel_tl 0x3
[BMCV VPP DUMP][error]  cb_coeff_sel_tr 0x0
[BMCV VPP DUMP][error]  cb_coeff_sel_bl 0x0
[BMCV VPP DUMP][error]  cb_coeff_sel_br 0x0
[BMCV VPP DUMP][error]  cr_coeff_sel_tl 0x3
[BMCV VPP DUMP][error]  cr_coeff_sel_tr 0x0
[BMCV VPP DUMP][error]  cr_coeff_sel_bl 0x0
[BMCV VPP DUMP][error]  cr_coeff_sel_br 0x0
[BMCV VPP DUMP][error]  dst_crop_height 0x2d0
[BMCV VPP DUMP][error]  dst_crop_width 0x240
[BMCV VPP DUMP][error]  dst_crop_st_x 0x0
[BMCV VPP DUMP][error]  dst_crop_st_y 0x0
[BMCV VPP DUMP][error]  dst_base_ext_ch0 0x4
[BMCV VPP DUMP][error]  dst_base_ext_ch1 0x0
[BMCV VPP DUMP][error]  dst_base_ext_ch2 0x0
[BMCV VPP DUMP][error]  dst_base_ext_ch3 0x0
[BMCV VPP DUMP][error]  dst_base_ch0 0x40000000
[BMCV VPP DUMP][error]  dst_base_ch1 0x0
[BMCV VPP DUMP][error]  dst_base_ch2 0x0
[BMCV VPP DUMP][error]  dst_base_ch3 0x0
[BMCV VPP DUMP][error]  dst_stride_ch0 0x6c0
[BMCV VPP DUMP][error]  dst_stride_ch1 0x0
[BMCV VPP DUMP][error]  dst_stride_ch2 0x0
[BMCV VPP DUMP][error]  dst_stride_ch3 0x0
[BMCV VPP DUMP][error]  csc_coe00  1.000000
[BMCV VPP DUMP][error]  csc_coe01  0.000000
[BMCV VPP DUMP][error]  csc_coe02  1.401886
[BMCV VPP DUMP][error]  csc_add0  -179.441452
[BMCV VPP DUMP][error]  csc_coe10  1.000000
[BMCV VPP DUMP][error]  csc_coe11  -0.345807
[BMCV VPP DUMP][error]  csc_coe12  -0.714903
[BMCV VPP DUMP][error]  csc_add1  135.770813
[BMCV VPP DUMP][error]  csc_coe20  1.000000
[BMCV VPP DUMP][error]  csc_coe21  1.770983
[BMCV VPP DUMP][error]  csc_coe22  0.000000
[BMCV VPP DUMP][error]  csc_add2  -226.685760
[BMCV VPP DUMP][error]  con_bri_a_0  0.000000
[BMCV VPP DUMP][error]  con_bri_a_1  0.000000
[BMCV VPP DUMP][error]  con_bri_a_2  0.000000
[BMCV VPP DUMP][error]  con_bri_b_0  0.000000
[BMCV VPP DUMP][error]  con_bri_b_1  0.000000
[BMCV VPP DUMP][error]  con_bri_b_2  0.000000
[BMCV VPP DUMP][error]  con_bri_round 0x1
[BMCV VPP DUMP][error]  con_bri_full 0x0
[BMCV VPP DUMP][error]  hr_csc_f2i_round 0x1
[BMCV VPP DUMP][error]  hr_csc_i2f_round 0x1
[BMCV VPP DUMP][error]  post_padding_value_ch0  0.000000
[BMCV VPP DUMP][error]  post_padding_value_ch1  0.000000
[BMCV VPP DUMP][error]  post_padding_value_ch2  0.000000
[BMCV VPP DUMP][error]  post_padding_value_ch3  0.000000
[BMCV VPP DUMP][error]  post_padding_ext_up 0x0
[BMCV VPP DUMP][error]  post_padding_ext_bot 0x0
[BMCV VPP DUMP][error]  post_padding_ext_left 0x0
[BMCV VPP DUMP][error]  post_padding_ext_right 0x0
[BMCV VPP DUMP][error]  scl_ctrl 0x1
[BMCV VPP DUMP][error]  scl_init_x 0x0
[BMCV VPP DUMP][error]  scl_init_y 0x0
[BMCV VPP DUMP][error]  scl_x 1.000000
[BMCV VPP DUMP][error]  scl_y 1.000000
[BMCV VPP DUMP][error]  map_conv_comp_ext_y 0x0
[BMCV VPP DUMP][error]  map_conv_comp_ext_c 0x0
[BMCV VPP DUMP][error]  map_conv_off_base_ext_y 0x0
[BMCV VPP DUMP][error]  map_conv_off_base_ext_c 0x0
[BMCV VPP DUMP][error]  map_conv_off_base_y 0x0
[BMCV VPP DUMP][error]  map_conv_off_base_c 0x0
[BMCV VPP DUMP][error]  map_conv_pic_height_y 0x0
[BMCV VPP DUMP][error]  map_conv_pic_height_c 0x0
[BMCV VPP DUMP][error]  map_conv_comp_base_y 0x0
[BMCV VPP DUMP][error]  map_conv_comp_base_c 0x0
[BMCV VPP DUMP][error]  map_conv_comp_stride_y 0x0
[BMCV VPP DUMP][error]  map_conv_comp_stride_c 0x0
[BMCV VPP DUMP][error]  map_conv_crop_st_y 0x0
[BMCV VPP DUMP][error]  map_conv_crop_st_x 0x0
[BMCV VPP DUMP][error]  map_conv_crop_height 0x0
[BMCV VPP DUMP][error]  map_conv_crop_width 0x0
[BMCV VPP DUMP][error]  map_conv_out_mode_y 0x0
[BMCV VPP DUMP][error]  map_conv_out_mode_c 0x0
[BMCV VPP DUMP][error]  map_conv_hsync_period 0x0
[BMCV VPP DUMP][error]  map_conv_bit_depth_y 0x0
[BMCV VPP DUMP][error]  map_conv_bit_depth_c 0x0
[BMCV VPP DUMP][error]  map_conv_offset_endian 0x0
[BMCV VPP DUMP][error]  map_conv_comp_endian 0x0
[BMCV VPP DUMP][error]  map_conv_time_out_cnt 0x0
/home/jenkins/workspace/sophon-sdk/build_sophon-mw-6/middleware-soc/bm_opencv/modules/imgcodecs/src/grfmt_bmjpeg.cpp:907            [dec_convert] Error:failed to convert
imread_('/home/linaro/yolov8_seg/test_img/1.jpg'): can't read data: OpenCV(4.1.0) /home/jenkins/workspace            /sophon-sdk/build_sophon-mw-6/middleware-soc/bm_opencv/modules/imgcodecs/src/grfmt_bmjpeg.cpp:1136: error: (-215:Asserti            on failed) BM_SUCCESS == dec_convert(img, info.actual_frame_height, info.actual_frame_width, p_phys_addr, info.cb_offset            , info.cr_offset, src_stride, dst_stride, src_fmt, csc_type) in function 'outputMat'

Error! src size is abnormal:width=0,height=0

![image](https://github.com/user-attachments/assets/ef33449d-2a88-45d5-9929-149cfb90d671)

**Comment by sophon-leevi** [comment]
这个libsophon不对，要拿带-soc-的

**Comment by lrjj** [comment]
可以了，谢谢~
