### ISSUE TITLE
可以在x86_64系统的docker里运行吗

### ISSUE THREAD

**Issue by xunfeng2zkj** [sophgo/sophon-demo#69]
root@5d7982dd6596:/workspace/sophon-demo/sample/YOLOv8_pose/cpp/yolov8_bmcv/build# cmake ..
build in debug mode
cur dir: /workspace/sophon-demo/sample/YOLOv8_pose/cpp/yolov8_bmcv
pcie mode, starting......
-- Configuring done
-- Generating done
-- Build files have been written to: /workspace/sophon-demo/sample/YOLOv8_pose/cpp/yolov8_bmcv/build
root@5d7982dd6596:/workspace/sophon-demo/sample/YOLOv8_pose/cpp/yolov8_bmcv/build# make
[ 25%] Linking CXX executable /workspace/sophon-demo/sample/YOLOv8_pose/cpp/yolov8_bmcv/yolov8_bmcv.pcie
/usr/bin/ld: /opt/sophon/sophon-ffmpeg_0.10.0/lib/libavcodec.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/yolov8_bmcv.pcie.dir/build.make:155: /workspace/sophon-demo/sample/YOLOv8_pose/cpp/yolov8_bmcv/yolov8_bmcv.pcie] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/yolov8_bmcv.pcie.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
-----------------------------------------------------
目前在系统里编译好了sophgo-sail，但是编译yolov8_pose不成功，是要用交叉编译吗

**Comment by sophon-leevi** [comment]
看报错，像是你在x86服务器上装了arm的sdk和驱动，这是不对的。
请阅读[readme](https://github.com/sophgo/sophon-demo/blob/release/sample/YOLOv8_pose/cpp/README.md)。
如果你用的tpu是加速卡的形式（如SC7），插在服务器上，那应该安装x86版本的sdk和驱动，可以直接在x86服务器上，使用pcie模式编译。
如果用的tpu是边缘服务器的形式（如SE7），那么应该参考soc模式去做交叉编译。
