### ISSUE TITLE
ff_decode.hpp 函数和 ff_decode.cpp 不一致

### ISSUE THREAD

**Issue by joeduff** [sophgo/sophon-demo#7]
ff_decode.hpp : 
     bm_status_t avframe_to_bm_image(bm_handle_t &handle, AVFrame *in, bm_image *out, bool is_jpeg);
ff_decode.cpp : 
     bm_status_t avframe_to_bm_image(bm_handle_t& handle, AVFrame* in, bm_image* out, bool is_jpeg, bool data_on_device_mem)

**Comment by gfwsbsbsb** [comment]
已修复
