### ISSUE TITLE
bmodel推理时数据转换问题

### ISSUE THREAD

**Issue by Dawsonqw** [sophgo/sophon-demo#74]
我利用tpu-mlir将一个网络转换成了多个bmodel，中间有个bmodel的输出为fp32，接下来一个将其输出作为输入的bmodel的数据类型被转换成了fp16，我想用bm_memcpy_d2d_byte这个接口进行在device进行数据搬运，但是这种情况该接口无法处理，有什么相关的接口可以直接在device端进行数据转换吗？或者怎么控制转换onnx时保证上下两个bmodel的输入输出数据类型一致呢？

**Comment by sophon-leevi** [comment]
model_deploy的时候，添加--quant_input和--quant_output参数，这样bmodel 的输入输出数据类型就会和onnx保持一致

**Comment by Dawsonqw** [comment]
> model_deploy的时候，添加--quant_input和--quant_output参数，这样bmodel 的输入输出数据类型就会和onnx保持一致

好的，那请问这个有相关接口能在推理bmodel过程中完成数据转换吗？沿用当前情况，上一个bmodel的输出是fp32的数据，下一个bmodel的输入是fp16的数据类型，目前能想到的是把数据从device端搬到host后做数据转换后再搬回去，但这样效率很低，目前翻了一下文档似乎没有这样的接口能直接在device端做数据转换。

**Comment by sophon-leevi** [comment]
用户层目前没有暴露这种转fp16的接口，建议还是在转模型的时候就尽量避免这种需要数据类型转换的情况。
