### ISSUE TITLE
是否能够支持 Qwen/Qwen2.5-3B-Instruct

### ISSUE THREAD

**Issue by myboyliu2025** [sophgo/sophon-demo#77]
# bm1684x 单芯
./scripts/gen_bmodel.sh --target bm1684x --mode int4 --name qwen-7b --seq_length 512 --addr_mode io_alone
目前这个脚本不支持3b,通过修改脚本指定"hidden_size": 2048,转换生成bmodel，输出内容乱码。

**Comment by sophon-leevi** [comment]
https://github.com/sophgo/LLM-TPU/tree/main/models/Qwen2_5/compile/files/Qwen2.5-3B-Instruct 
这个repo有支持3b，需要做修改的地方应该包括modelling文件、onnx导出脚本、模型编译脚本。
