### ISSUE TITLE
Qwen2.5模型 32k上下文长度生成onnx会kill

### ISSUE THREAD

**Issue by myboyliu2025** [sophgo/sophon-demo#78]
描述：
在bm1684x单芯片上处理Qwen2.5模型时，使用命令：
bash
python3 tools/export_onnx_qwen2_5.py --model_path /workspace/Qwen2.5-7B-Instruct --seq_length 32000
需要32k的上下文长度，但使用上述命令会导致进程被终止（kill）。

**Comment by sophon-leevi** [comment]
kill是你的主机内存太小了。
